//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectMessageMapper.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObjectMessageMapper.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        internal static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Error with 0 item. {0}.
        /// </summary>
        internal static string COMMUNICATION_ERROR_0 {
            get {
                return ResourceManager.GetString("COMMUNICATION_ERROR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Error with 1 item. {0}.
        /// </summary>
        internal static string COMMUNICATION_ERROR_1 {
            get {
                return ResourceManager.GetString("COMMUNICATION_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Error with 2 item. {0}.
        /// </summary>
        internal static string COMMUNICATION_ERROR_2 {
            get {
                return ResourceManager.GetString("COMMUNICATION_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicaiton Instance.
        /// </summary>
        internal static string ENTITY_APPLICATION_INSTANCE {
            get {
                return ResourceManager.GetString("ENTITY_APPLICATION_INSTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string ENTITY_CUSTOMER {
            get {
                return ResourceManager.GetString("ENTITY_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string EntityUser {
            get {
                return ResourceManager.GetString("EntityUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Actor.
        /// </summary>
        internal static string ENUM_ACTOR {
            get {
                return ResourceManager.GetString("ENUM_ACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Type.
        /// </summary>
        internal static string ENUM_OWNER_TYPE {
            get {
                return ResourceManager.GetString("ENUM_OWNER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        internal static string ENUM_USER_TYPE {
            get {
                return ResourceManager.GetString("ENUM_USER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown User Type.
        /// </summary>
        internal static string ENUM_USER_TYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("ENUM_USER_TYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found..
        /// </summary>
        internal static string EXCEPTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("EXCEPTION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data constraint..
        /// </summary>
        internal static string INVALID_CONSTRAINT {
            get {
                return ResourceManager.GetString("INVALID_CONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s just right!.
        /// </summary>
        internal static string JUST_RIGHT {
            get {
                return ResourceManager.GetString("JUST_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more licenses are available..
        /// </summary>
        internal static string NO_LICENSES {
            get {
                return ResourceManager.GetString("NO_LICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s over it&apos;s limit..
        /// </summary>
        internal static string OVER_LIMIT {
            get {
                return ResourceManager.GetString("OVER_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access..
        /// </summary>
        internal static string PERMISSION_DENIED {
            get {
                return ResourceManager.GetString("PERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string READ_ONLY {
            get {
                return ResourceManager.GetString("READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RESULT_SUCCESS {
            get {
                return ResourceManager.GetString("RESULT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occured on the server..
        /// </summary>
        internal static string SERVER_ERROR {
            get {
                return ResourceManager.GetString("SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server was not found..
        /// </summary>
        internal static string SERVER_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server was not found. For help, click the following.\n\n\{0}.
        /// </summary>
        internal static string SERVER_NOT_FOUND2 {
            get {
                return ResourceManager.GetString("SERVER_NOT_FOUND2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is too busy and the moment to handle your request. Please try again later..
        /// </summary>
        internal static string SERVER_TO_BUSY {
            get {
                return ResourceManager.GetString("SERVER_TO_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s under it&apos;s limit..
        /// </summary>
        internal static string UNDER_LIMIT {
            get {
                return ResourceManager.GetString("UNDER_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server was not found..
        /// </summary>
        internal static string UNKNOWN_SERVER_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_SERVER_ERROR", resourceCulture);
            }
        }
    }
}
